# Generated by Django 5.2.13 on 2026-04-24 23:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Foto')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de matrícula')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('guardian_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do responsável')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do responsável')),
                ('guardian_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF do responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor (HEX)')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belts', to='alunos.modality')),
            ],
            options={
                'verbose_name': 'Faixa',
                'verbose_name_plural': 'Faixas',
                'ordering': ['modality', 'order'],
                'unique_together': {('modality', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StudentGraduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateField(verbose_name='Data da graduação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.belt', verbose_name='Faixa')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.modality', verbose_name='Modalidade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='alunos.student')),
            ],
            options={
                'verbose_name': 'Graduação',
                'verbose_name_plural': 'Graduações',
                'ordering': ['-graduation_date'],
            },
        ),
    ]
