# Generated by Django 5.2.13 on 2026-04-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='belt',
            name='color_hex_2',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Segunda Cor (HEX)'),
        ),
    ]
