# Generated by Django 5.2.13 on 2026-04-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_belt_color_hex_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='seed_key',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
