# Generated by Django 5.2.13 on 2026-04-24 23:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do plano')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('modalities', models.ManyToManyField(blank=True, to='alunos.modality', verbose_name='Modalidades incluídas')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Desconto (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_enrollments', to='alunos.student', verbose_name='Aluno')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Matrícula Financeira',
                'verbose_name_plural': 'Matrículas Financeiras',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.DateField(verbose_name='Mês de referência')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto (R$)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('pix', 'PIX'), ('debit_card', 'Cartão de Débito'), ('credit_card', 'Cartão de Crédito'), ('bank_slip', 'Boleto'), ('transfer', 'Transferência Bancária')], max_length=20, verbose_name='Forma de pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.financialenrollment', verbose_name='Matrícula')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fees', to='alunos.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['-due_date'],
                'unique_together': {('student', 'reference_month')},
            },
        ),
    ]
